name: Crops_diagnosis
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.3.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.1+3
  modal_progress_hud: ^0.1.3
  #---
  http:
  json_annotation:
  path_provider:
  quiver:
  image_picker:
  firebase_storage:
  firebase_analytics: ^5.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
